# (The MIT License)
#
# Copyright (c) 2024-2025 Yegor Bugayenko
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the 'Software'), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
name: Check fans format

'on':
  pull_request:
    branches: [master]
    paths:
      - index.html

jobs:
  check-format:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run the format validation script and check for changes
      - name: Validate fans list format
        run: |
          echo "Checking for changes in fans list format..."
          git status
          python format_fans.py
          CHANGED_FILES=$(git diff --name-only)

          if echo "$CHANGED_FILES" | grep -q "index.html"; then
            echo "ERROR: The file 'index.html' has been modified by the formatter."
            echo "------ Detected Changes ------"
            git diff
            echo "--------------------------------"
            echo "You can download the modified file from the artifact here:"
            echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            echo "Alternatively, run the test locally using:"
            echo "  python format_fans.py"
            exit 1
          else
            echo "Fans list format is valid. No changes detected."
          fi

      # Upload the modified file if the validation fails
      - name: Upload modified files
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: index-modified-html
          path: index.html
